cc_binary(
    name = "utf",
    srcs = ["main.cpp"],
    copts = [
        "/std:c++17",
        "/DWIN32_LEAN_AND_MEAN",
        "/DNOMINMAX",
        "/D_CRT_SECURE_NO_WARNINGS",
    ],
    linkopts = [],
)
